# Generated by Django 4.2.13 on 2024-05-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_auto_20240521_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
